import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI Book
  bookSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Chapter 1: Foundations of Physical AI',
      collapsed: false,
      items: [
        'chapter-1/index',
        'chapter-1/introduction',
        'chapter-1/lesson-1-1',
        'chapter-1/lesson-1-2',
        'chapter-1/lesson-1-3',
        'chapter-1/case-study',
        'chapter-1/mini-project',
        'chapter-1/summary',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: Agents & Environments',
      collapsed: false,
      items: [
        'chapter-2/index',
        'chapter-2/introduction',
        'chapter-2/lesson-2-1',
        'chapter-2/lesson-2-2',
        'chapter-2/lesson-2-3',
        'chapter-2/case-study',
        'chapter-2/mini-project',
        'chapter-2/summary',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Learning & Control',
      collapsed: false,
      items: [
        'chapter-3/index',
        'chapter-3/introduction',
        'chapter-3/lesson-3-1',
        'chapter-3/lesson-3-2',
        'chapter-3/lesson-3-3',
        'chapter-3/case-study',
        'chapter-3/mini-project',
        'chapter-3/summary',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Physical AI in the Real World',
      collapsed: false,
      items: [
        'chapter-4/index',
        'chapter-4/introduction',
        'chapter-4/lesson-4-1',
        'chapter-4/lesson-4-2',
        'chapter-4/lesson-4-3',
        'chapter-4/case-study',
        'chapter-4/mini-project',
        'chapter-4/summary',
      ],
    },
  ],
};

export default sidebars;